package bedrock

import (
	"github.com/aws/aws-cdk-go/awscdk/v2/awsbedrock"
)

// Experimental.
type AgentActionGroupProps struct {
	// The name of the action group.
	// Default: - a name is generated by CloudFormation.
	//
	// Experimental.
	ActionGroupName *string `field:"required" json:"actionGroupName" yaml:"actionGroupName"`
	// Experimental.
	ActionGroupExecutor *ActionGroupExecutor `field:"optional" json:"actionGroupExecutor" yaml:"actionGroupExecutor"`
	// Specifies whether the action group is available for the agent to invoke or not when sending an InvokeAgent request.
	// Experimental.
	ActionGroupState *string `field:"optional" json:"actionGroupState" yaml:"actionGroupState"`
	// Contains details about the S3 object containing the OpenAPI schema for the action group.
	//
	// For more information, see
	// [Action group OpenAPI schemas](https://docs.aws.amazon.com/bedrock/latest/userguide/agents-api-schema.html).
	// Experimental.
	ApiSchema ApiSchema `field:"optional" json:"apiSchema" yaml:"apiSchema"`
	// A description of the action group.
	// Experimental.
	Description *string `field:"optional" json:"description" yaml:"description"`
	// Defines functions that each define parameters that the agent needs to invoke from the user.
	// Experimental.
	FunctionSchema *awsbedrock.CfnAgent_FunctionSchemaProperty `field:"optional" json:"functionSchema" yaml:"functionSchema"`
	// If you specify this value as AMAZON.UserInput, the agent will prompt additional information from the user when it doesn't have enough information to respond to an utterance. Leave this field blank if you don't want the agent to prompt additional information.
	// Experimental.
	ParentActionGroupSignature *string `field:"optional" json:"parentActionGroupSignature" yaml:"parentActionGroupSignature"`
	// Specifies whether the agent should skip the resource in use check on delete.
	// Experimental.
	SkipResourceInUseCheckOnDelete *bool `field:"optional" json:"skipResourceInUseCheckOnDelete" yaml:"skipResourceInUseCheckOnDelete"`
}

