package bedrock

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/generative-ai-cdk-constructs-go/generative-ai-cdk-constructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsbedrock"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/constructs-go/constructs/v10"
)

// Class to create a ApplicationInferenceProfile with CDK.
//
// These are inference profiles created by users (user defined).
// This helps to track costs and model usage.
// See: https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-create.html
//
// Experimental.
type ApplicationInferenceProfile interface {
	InferenceProfileBase
	IInvokable
	// Time Stamp for ApplicationInferenceProfile creation.
	// Experimental.
	CreatedAt() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	// Experimental.
	Env() *awscdk.ResourceEnvironment
	// The ARN of the application application inference profile.
	// Experimental.
	InferenceProfileArn() *string
	// The unique identifier of the application inference profile.
	// Experimental.
	InferenceProfileId() *string
	// The underlying model/cross-region model used by the application inference profile.
	// Experimental.
	InferenceProfileModel() IInvokable
	// The name of the application inference profile.
	// Experimental.
	InferenceProfileName() *string
	// This equals to the inferenceProfileArn property, useful just to implement IInvokable interface.
	// Experimental.
	InvokableArn() *string
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// The status of the application inference profile.
	//
	// ACTIVE means that the inference profile is ready to be used.
	// Experimental.
	Status() *string
	// The type of the inference profile.
	//
	// The following types are possible:
	// SYSTEM_DEFINED – The inference profile is defined by Amazon Bedrock.
	// You can route inference requests across regions with these inference profiles.
	// APPLICATION – The inference profile was created by a user.
	// This type of inference profile can track metrics and costs when invoking the model in it.
	// The inference profile may route requests to one or multiple regions.
	// Experimental.
	Type() InferenceProfileType
	// Time Stamp for ApplicationInferenceProfile update.
	// Experimental.
	UpdatedAt() *string
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Gives the appropriate policies to invoke and use the application inference profile.
	// Experimental.
	GrantInvoke(grantee awsiam.IGrantable) awsiam.Grant
	// Grants appropriate permissions to use the application inference profile (AIP).
	//
	// Does not grant permissions to use the model/cross-region profile in the AIP.
	// Experimental.
	GrantProfileUsage(grantee awsiam.IGrantable) awsiam.Grant
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for ApplicationInferenceProfile
type jsiiProxy_ApplicationInferenceProfile struct {
	jsiiProxy_InferenceProfileBase
	jsiiProxy_IInvokable
}

func (j *jsiiProxy_ApplicationInferenceProfile) CreatedAt() *string {
	var returns *string
	_jsii_.Get(
		j,
		"createdAt",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) InferenceProfileArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"inferenceProfileArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) InferenceProfileId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"inferenceProfileId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) InferenceProfileModel() IInvokable {
	var returns IInvokable
	_jsii_.Get(
		j,
		"inferenceProfileModel",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) InferenceProfileName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"inferenceProfileName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) InvokableArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"invokableArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) Status() *string {
	var returns *string
	_jsii_.Get(
		j,
		"status",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) Type() InferenceProfileType {
	var returns InferenceProfileType
	_jsii_.Get(
		j,
		"type",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApplicationInferenceProfile) UpdatedAt() *string {
	var returns *string
	_jsii_.Get(
		j,
		"updatedAt",
		&returns,
	)
	return returns
}


// Experimental.
func NewApplicationInferenceProfile(scope constructs.Construct, id *string, props *ApplicationInferenceProfileProps) ApplicationInferenceProfile {
	_init_.Initialize()

	if err := validateNewApplicationInferenceProfileParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_ApplicationInferenceProfile{}

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.ApplicationInferenceProfile",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewApplicationInferenceProfile_Override(a ApplicationInferenceProfile, scope constructs.Construct, id *string, props *ApplicationInferenceProfileProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.ApplicationInferenceProfile",
		[]interface{}{scope, id, props},
		a,
	)
}

// Import a ApplicationInferenceProfile given its attributes.
// Experimental.
func ApplicationInferenceProfile_FromApplicationInferenceProfileAttributes(scope constructs.Construct, id *string, attrs *ApplicationInferenceProfileAttributes) IInferenceProfile {
	_init_.Initialize()

	if err := validateApplicationInferenceProfile_FromApplicationInferenceProfileAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IInferenceProfile

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.ApplicationInferenceProfile",
		"fromApplicationInferenceProfileAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Import a low-level L1 Cfn ApplicationInferenceProfile.
// Experimental.
func ApplicationInferenceProfile_FromCfnApplicationInferenceProfile(CfnApplicationInferenceProfile awsbedrock.CfnApplicationInferenceProfile) IInferenceProfile {
	_init_.Initialize()

	if err := validateApplicationInferenceProfile_FromCfnApplicationInferenceProfileParameters(CfnApplicationInferenceProfile); err != nil {
		panic(err)
	}
	var returns IInferenceProfile

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.ApplicationInferenceProfile",
		"fromCfnApplicationInferenceProfile",
		[]interface{}{CfnApplicationInferenceProfile},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func ApplicationInferenceProfile_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateApplicationInferenceProfile_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.ApplicationInferenceProfile",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func ApplicationInferenceProfile_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateApplicationInferenceProfile_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.ApplicationInferenceProfile",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func ApplicationInferenceProfile_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateApplicationInferenceProfile_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.ApplicationInferenceProfile",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApplicationInferenceProfile) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := a.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (a *jsiiProxy_ApplicationInferenceProfile) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApplicationInferenceProfile) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := a.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApplicationInferenceProfile) GetResourceNameAttribute(nameAttr *string) *string {
	if err := a.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApplicationInferenceProfile) GrantInvoke(grantee awsiam.IGrantable) awsiam.Grant {
	if err := a.validateGrantInvokeParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		a,
		"grantInvoke",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApplicationInferenceProfile) GrantProfileUsage(grantee awsiam.IGrantable) awsiam.Grant {
	if err := a.validateGrantProfileUsageParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		a,
		"grantProfileUsage",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApplicationInferenceProfile) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

