package bedrock

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/generative-ai-cdk-constructs-go/generative-ai-cdk-constructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsbedrock"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	"github.com/aws/constructs-go/constructs/v10"
)

// Class to create a Guardrail with CDK.
// Experimental.
type Guardrail interface {
	GuardrailBase
	// The content filters applied by the guardrail.
	// Experimental.
	ContentFilters() *[]*ContentFilter
	// The contextual grounding filters applied by the guardrail.
	// Experimental.
	ContextualGroundingFilters() *[]*ContextualGroundingFilter
	// The denied topic filters applied by the guardrail.
	// Experimental.
	DeniedTopics() *[]Topic
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	// Experimental.
	Env() *awscdk.ResourceEnvironment
	// The ARN of the guardrail.
	// Experimental.
	GuardrailArn() *string
	// The ID of the guardrail.
	// Experimental.
	GuardrailId() *string
	// The version of the guardrail.
	//
	// By default, this value will always be `DRAFT` unless an explicit version is created.
	// For an explicit version created, this will usually be a number (e.g. for Version 1 just enter "1")
	//
	// Example:
	//   "1"
	//
	// Default: - "DRAFT".
	//
	// Experimental.
	GuardrailVersion() *string
	// Experimental.
	SetGuardrailVersion(val *string)
	// The computed hash of the guardrail properties.
	// Experimental.
	Hash() *string
	// The KMS key used to encrypt data.
	// Default: undefined - "Data is encrypted by default with a key that AWS owns and manages for you".
	//
	// Experimental.
	KmsKey() awskms.IKey
	// The managed word list filters applied by the guardrail.
	// Experimental.
	ManagedWordListFilters() *[]ManagedWordFilterType
	// The name of the guardrail.
	// Experimental.
	Name() *string
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The PII filters applied by the guardrail.
	// Experimental.
	PiiFilters() *[]*PIIFilter
	// The regex filters applied by the guardrail.
	// Experimental.
	RegexFilters() *[]*RegexFilter
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// The word filters applied by the guardrail.
	// Experimental.
	WordFilters() *[]*string
	// Adds a content filter to the guardrail.
	// Experimental.
	AddContentFilter(filter *ContentFilter)
	// Adds a contextual grounding filter to the guardrail.
	// Experimental.
	AddContextualGroundingFilter(filter *ContextualGroundingFilter)
	// Adds a denied topic filter to the guardrail.
	// Experimental.
	AddDeniedTopicFilter(filter Topic)
	// Adds a managed word list filter to the guardrail.
	// Experimental.
	AddManagedWordListFilter(filter ManagedWordFilterType)
	// Adds a PII filter to the guardrail.
	// Experimental.
	AddPIIFilter(filter *PIIFilter)
	// Adds a regex filter to the guardrail.
	// Experimental.
	AddRegexFilter(filter *RegexFilter)
	// Adds a word filter to the guardrail.
	// Experimental.
	AddWordFilter(filter *string)
	// Adds a word filter to the guardrail.
	// Experimental.
	AddWordFilterFromFile(filePath *string)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Create a version for the guardrail.
	//
	// Returns: The guardrail version.
	// Experimental.
	CreateVersion(description *string) *string
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Grant the given identity permissions to apply the guardrail.
	// Experimental.
	GrantApply(grantee awsiam.IGrantable) awsiam.Grant
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for Guardrail
type jsiiProxy_Guardrail struct {
	jsiiProxy_GuardrailBase
}

func (j *jsiiProxy_Guardrail) ContentFilters() *[]*ContentFilter {
	var returns *[]*ContentFilter
	_jsii_.Get(
		j,
		"contentFilters",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) ContextualGroundingFilters() *[]*ContextualGroundingFilter {
	var returns *[]*ContextualGroundingFilter
	_jsii_.Get(
		j,
		"contextualGroundingFilters",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) DeniedTopics() *[]Topic {
	var returns *[]Topic
	_jsii_.Get(
		j,
		"deniedTopics",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) GuardrailArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"guardrailArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) GuardrailId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"guardrailId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) GuardrailVersion() *string {
	var returns *string
	_jsii_.Get(
		j,
		"guardrailVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) Hash() *string {
	var returns *string
	_jsii_.Get(
		j,
		"hash",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) KmsKey() awskms.IKey {
	var returns awskms.IKey
	_jsii_.Get(
		j,
		"kmsKey",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) ManagedWordListFilters() *[]ManagedWordFilterType {
	var returns *[]ManagedWordFilterType
	_jsii_.Get(
		j,
		"managedWordListFilters",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) PiiFilters() *[]*PIIFilter {
	var returns *[]*PIIFilter
	_jsii_.Get(
		j,
		"piiFilters",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) RegexFilters() *[]*RegexFilter {
	var returns *[]*RegexFilter
	_jsii_.Get(
		j,
		"regexFilters",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Guardrail) WordFilters() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"wordFilters",
		&returns,
	)
	return returns
}


// Experimental.
func NewGuardrail(scope constructs.Construct, id *string, props *GuardrailProps) Guardrail {
	_init_.Initialize()

	if err := validateNewGuardrailParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_Guardrail{}

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.Guardrail",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewGuardrail_Override(g Guardrail, scope constructs.Construct, id *string, props *GuardrailProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.Guardrail",
		[]interface{}{scope, id, props},
		g,
	)
}

func (j *jsiiProxy_Guardrail)SetGuardrailVersion(val *string) {
	if err := j.validateSetGuardrailVersionParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"guardrailVersion",
		val,
	)
}

// Import a low-level L1 Cfn Guardrail.
// Experimental.
func Guardrail_FromCfnGuardrail(cfnGuardrail awsbedrock.CfnGuardrail) IGuardrail {
	_init_.Initialize()

	if err := validateGuardrail_FromCfnGuardrailParameters(cfnGuardrail); err != nil {
		panic(err)
	}
	var returns IGuardrail

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.Guardrail",
		"fromCfnGuardrail",
		[]interface{}{cfnGuardrail},
		&returns,
	)

	return returns
}

// Import a guardrail given its attributes.
// Experimental.
func Guardrail_FromGuardrailAttributes(scope constructs.Construct, id *string, attrs *GuardrailAttributes) IGuardrail {
	_init_.Initialize()

	if err := validateGuardrail_FromGuardrailAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IGuardrail

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.Guardrail",
		"fromGuardrailAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func Guardrail_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateGuardrail_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.Guardrail",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func Guardrail_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGuardrail_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.Guardrail",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func Guardrail_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGuardrail_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.Guardrail",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_Guardrail) AddContentFilter(filter *ContentFilter) {
	if err := g.validateAddContentFilterParameters(filter); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addContentFilter",
		[]interface{}{filter},
	)
}

func (g *jsiiProxy_Guardrail) AddContextualGroundingFilter(filter *ContextualGroundingFilter) {
	if err := g.validateAddContextualGroundingFilterParameters(filter); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addContextualGroundingFilter",
		[]interface{}{filter},
	)
}

func (g *jsiiProxy_Guardrail) AddDeniedTopicFilter(filter Topic) {
	if err := g.validateAddDeniedTopicFilterParameters(filter); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addDeniedTopicFilter",
		[]interface{}{filter},
	)
}

func (g *jsiiProxy_Guardrail) AddManagedWordListFilter(filter ManagedWordFilterType) {
	if err := g.validateAddManagedWordListFilterParameters(filter); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addManagedWordListFilter",
		[]interface{}{filter},
	)
}

func (g *jsiiProxy_Guardrail) AddPIIFilter(filter *PIIFilter) {
	if err := g.validateAddPIIFilterParameters(filter); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addPIIFilter",
		[]interface{}{filter},
	)
}

func (g *jsiiProxy_Guardrail) AddRegexFilter(filter *RegexFilter) {
	if err := g.validateAddRegexFilterParameters(filter); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addRegexFilter",
		[]interface{}{filter},
	)
}

func (g *jsiiProxy_Guardrail) AddWordFilter(filter *string) {
	if err := g.validateAddWordFilterParameters(filter); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addWordFilter",
		[]interface{}{filter},
	)
}

func (g *jsiiProxy_Guardrail) AddWordFilterFromFile(filePath *string) {
	if err := g.validateAddWordFilterFromFileParameters(filePath); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addWordFilterFromFile",
		[]interface{}{filePath},
	)
}

func (g *jsiiProxy_Guardrail) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := g.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (g *jsiiProxy_Guardrail) CreateVersion(description *string) *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"createVersion",
		[]interface{}{description},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_Guardrail) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_Guardrail) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := g.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_Guardrail) GetResourceNameAttribute(nameAttr *string) *string {
	if err := g.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_Guardrail) GrantApply(grantee awsiam.IGrantable) awsiam.Grant {
	if err := g.validateGrantApplyParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		g,
		"grantApply",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_Guardrail) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

