package bedrock

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/generative-ai-cdk-constructs-go/generative-ai-cdk-constructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsbedrock"
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	"github.com/aws/constructs-go/constructs/v10"
)

// Sets up a web crawler data source to be added to a knowledge base.
// Experimental.
type WebCrawlerDataSource interface {
	DataSourceNew
	// The max rate at which pages are crawled.
	// Experimental.
	CrawlingRate() *float64
	// The unique identifier of the data source.
	//
	// Example:
	//   "JHUEVXUZMU"
	//
	// Experimental.
	DataSourceId() *string
	// The name of the data source.
	// Experimental.
	DataSourceName() *string
	// The type of data source.
	// Experimental.
	DataSourceType() DataSourceType
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	// Experimental.
	Env() *awscdk.ResourceEnvironment
	// The KMS key to use to encrypt the data source.
	// Experimental.
	KmsKey() awskms.IKey
	// The knowledge base associated with the data source.
	// Experimental.
	KnowledgeBase() IKnowledgeBase
	// The maximum number of pages to crawl.
	// Experimental.
	MaxPages() *float64
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The max rate at which pages are crawled.
	// Experimental.
	SiteUrls() *[]*string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Formats the data source configuration properties for CloudFormation.
	// Experimental.
	FormatAsCfnProps(props *DataSourceAssociationProps, dataSourceConfiguration *awsbedrock.CfnDataSource_DataSourceConfigurationProperty) *awsbedrock.CfnDataSourceProps
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Adds appropriate permissions to the KB execution role needed by the data source.
	// Experimental.
	HandleCommonPermissions(props *DataSourceAssociationProps)
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for WebCrawlerDataSource
type jsiiProxy_WebCrawlerDataSource struct {
	jsiiProxy_DataSourceNew
}

func (j *jsiiProxy_WebCrawlerDataSource) CrawlingRate() *float64 {
	var returns *float64
	_jsii_.Get(
		j,
		"crawlingRate",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) DataSourceId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"dataSourceId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) DataSourceName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"dataSourceName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) DataSourceType() DataSourceType {
	var returns DataSourceType
	_jsii_.Get(
		j,
		"dataSourceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) KmsKey() awskms.IKey {
	var returns awskms.IKey
	_jsii_.Get(
		j,
		"kmsKey",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) KnowledgeBase() IKnowledgeBase {
	var returns IKnowledgeBase
	_jsii_.Get(
		j,
		"knowledgeBase",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) MaxPages() *float64 {
	var returns *float64
	_jsii_.Get(
		j,
		"maxPages",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) SiteUrls() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"siteUrls",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WebCrawlerDataSource) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Experimental.
func NewWebCrawlerDataSource(scope constructs.Construct, id *string, props *WebCrawlerDataSourceProps) WebCrawlerDataSource {
	_init_.Initialize()

	if err := validateNewWebCrawlerDataSourceParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_WebCrawlerDataSource{}

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.WebCrawlerDataSource",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewWebCrawlerDataSource_Override(w WebCrawlerDataSource, scope constructs.Construct, id *string, props *WebCrawlerDataSourceProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.WebCrawlerDataSource",
		[]interface{}{scope, id, props},
		w,
	)
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func WebCrawlerDataSource_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateWebCrawlerDataSource_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.WebCrawlerDataSource",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func WebCrawlerDataSource_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWebCrawlerDataSource_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.WebCrawlerDataSource",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func WebCrawlerDataSource_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWebCrawlerDataSource_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.WebCrawlerDataSource",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WebCrawlerDataSource) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := w.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (w *jsiiProxy_WebCrawlerDataSource) FormatAsCfnProps(props *DataSourceAssociationProps, dataSourceConfiguration *awsbedrock.CfnDataSource_DataSourceConfigurationProperty) *awsbedrock.CfnDataSourceProps {
	if err := w.validateFormatAsCfnPropsParameters(props, dataSourceConfiguration); err != nil {
		panic(err)
	}
	var returns *awsbedrock.CfnDataSourceProps

	_jsii_.Invoke(
		w,
		"formatAsCfnProps",
		[]interface{}{props, dataSourceConfiguration},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WebCrawlerDataSource) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WebCrawlerDataSource) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := w.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WebCrawlerDataSource) GetResourceNameAttribute(nameAttr *string) *string {
	if err := w.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WebCrawlerDataSource) HandleCommonPermissions(props *DataSourceAssociationProps) {
	if err := w.validateHandleCommonPermissionsParameters(props); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"handleCommonPermissions",
		[]interface{}{props},
	)
}

func (w *jsiiProxy_WebCrawlerDataSource) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

