package kendra

import (
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
)

// Properties for creating a GenAI Index.
// Experimental.
type KendraGenAiIndexProps struct {
	// The document capacity units.
	//
	// Every unit increases the baseline capacity by 20,000 documents.
	// E.g. `documentCapacityUnits: 1` means Baseline + 20,000 documents = 40,000 documents
	// Default: 0 - baseline capacity of 20,000 documents.
	//
	// Experimental.
	DocumentCapacityUnits *float64 `field:"optional" json:"documentCapacityUnits" yaml:"documentCapacityUnits"`
	// The identifier of the AWS KMS customer managed key (CMK) to use to encrypt data indexed by Amazon Kendra.
	//
	// Amazon Kendra doesn't support
	// asymmetric CMKs.
	// Default: - AWS managed encryption key is used.
	//
	// Experimental.
	KmsKey awskms.IKey `field:"optional" json:"kmsKey" yaml:"kmsKey"`
	// The name of the index.
	// Default: - A name is generated by CDK.
	//
	// Experimental.
	Name *string `field:"optional" json:"name" yaml:"name"`
	// The query capacity units.
	//
	// Every unit increases the baseline capacity by 0.1 QPS.
	// E.g. `queryCapacityUnits: 7` means Baseline + 0.1 QPS * 7 = 0.8 QPS
	// Default: 0 - baseline capacity of 0.1 QPS
	//
	// Experimental.
	QueryCapacityUnits *float64 `field:"optional" json:"queryCapacityUnits" yaml:"queryCapacityUnits"`
}

