package generative-ai-cdk-constructs

import (
	"github.com/aws/aws-cdk-go/awscdk/v2/awss3"
)

// Properties for creating a CDK BDA construct.
// Experimental.
type BedrockDataAutomationProps struct {
	// - Optional.
	//
	// The S3 bucket
	// for input data used by the Bedrock Data Automation process.
	// If not provided, a new bucket will be created.
	// Experimental.
	InputBucket awss3.IBucket `field:"optional" json:"inputBucket" yaml:"inputBucket"`
	// - Optional.
	//
	// Indicates whether a Bedrock Data
	// Automation invocation is required. If true, the necessary resources will be created.
	// Default: - false.
	//
	// Experimental.
	IsBDAInvocationRequired *bool `field:"optional" json:"isBDAInvocationRequired" yaml:"isBDAInvocationRequired"`
	// - Optional.
	//
	// Indicates whether a Bedrock Data
	// Automation project is required. If true, the necessary resources will be created.
	// Default: - false.
	//
	// Experimental.
	IsBDAProjectRequired *bool `field:"optional" json:"isBDAProjectRequired" yaml:"isBDAProjectRequired"`
	// - Optional.
	//
	// Indicates whether a custom
	// Bedrock Data Automation blueprint is required. If true, the necessary resources will be created.
	// Default: - false.
	//
	// Experimental.
	IsCustomBDABlueprintRequired *bool `field:"optional" json:"isCustomBDABlueprintRequired" yaml:"isCustomBDABlueprintRequired"`
	// - Optional.
	//
	// Indicates whether the status of the
	// Bedrock Data Automation process is required. If true, the necessary resources will be created.
	// Default: - false.
	//
	// Experimental.
	IsStatusRequired *bool `field:"optional" json:"isStatusRequired" yaml:"isStatusRequired"`
	// - Optional.
	//
	// The S3 bucket for storing
	// output files generated by the Bedrock Data Automation process.
	// Experimental.
	OutputBucket awss3.IBucket `field:"optional" json:"outputBucket" yaml:"outputBucket"`
}

