package bedrock

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/generative-ai-cdk-constructs-go/generativeaicdkconstructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/cdklabs/generative-ai-cdk-constructs-go/generativeaicdkconstructs/neptune"
)

// Creates a new Amazon Bedrock Knowledge Base using a Neptune Analytics vector store, this is also known as GraphRAG.
//
// GraphRAG is a capability that combines graph modeling with generative AI to enhance retrieval-augmented generation (RAG).
// It automatically identifies and leverages relationships between entities and structural elements within documents,
// enabling more comprehensive and contextually relevant responses from foundation models.
//
// Key benefits:
// - More relevant responses by leveraging relationships between entities and structural elements across documents
// - Enhanced search capabilities that connect content through multiple logical steps
// - Better cross-document reasoning for more precise and contextually accurate answers
// - Reduced hallucinations through improved information connectivity
//
// Limitations:
// - AWS PrivateLink VPC endpoint connectivity is not supported
// - Graph build configuration options are not customizable
// - Autoscaling is not supported for Neptune Analytics graphs
// - Only supports Amazon S3 as data source
// - Uses Claude 3 Haiku model for automatic graph building with contextual enrichment
// - Each data source limited to 1000 files (can be increased to max 10000 files).
// See: https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-build-graphs.html
//
// Experimental.
type GraphKnowledgeBase interface {
	GraphKnowledgeBaseBase
	// The description of the knowledge base.
	// Experimental.
	Description() *string
	// The embeddings model for the knowledge base.
	// Experimental.
	EmbeddingModel() BedrockFoundationModel
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Experimental.
	Env() *interfaces.ResourceEnvironment
	// The vector field mapping configuration.
	// Experimental.
	FieldMapping() *VectorFieldMapping
	// Experimental.
	Graph() neptune.INeptuneGraph
	// A narrative instruction of the knowledge base.
	//
	// A Bedrock Agent can use this instruction to determine if it should
	// query this Knowledge Base.
	// Experimental.
	Instruction() *string
	// The ARN of the knowledge base.
	// Experimental.
	KnowledgeBaseArn() *string
	// The ID of the knowledge base.
	// Experimental.
	KnowledgeBaseId() *string
	// The name of the knowledge base.
	// Experimental.
	Name() *string
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Experimental.
	Notebook() neptune.NeptuneGraphNotebook
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The role associated with the knowledge base.
	// Experimental.
	Role() awsiam.IRole
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// The type of knowledge base.
	// Experimental.
	Type() KnowledgeBaseType
	// The storage type for the Vector Embeddings.
	// Experimental.
	VectorStoreType() VectorStoreType
	// Add a Confluence data source to the knowledge base.
	// Experimental.
	AddConfluenceDataSource(props *ConfluenceDataSourceAssociationProps) ConfluenceDataSource
	// Add a Custom data source to the knowledge base.
	// Experimental.
	AddCustomDataSource(props *CustomDataSourceAssociationProps) CustomDataSource
	// Adds an S3 data source to the knowledge base.
	// Experimental.
	AddS3DataSource(props *S3DataSourceAssociationProps) S3DataSource
	// Add a Salesforce data source to the knowledge base.
	// Experimental.
	AddSalesforceDataSource(props *SalesforceDataSourceAssociationProps) SalesforceDataSource
	// Add a SharePoint data source to the knowledge base.
	// Experimental.
	AddSharePointDataSource(props *SharePointDataSourceAssociationProps) SharePointDataSource
	// Add a web crawler data source to the knowledge base.
	// Experimental.
	AddWebCrawlerDataSource(props *WebCrawlerDataSourceAssociationProps) WebCrawlerDataSource
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Grant the given principal identity permissions to perform actions on this knowledge base.
	// Experimental.
	Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant
	// Grant the given identity permissions to query the knowledge base.
	//
	// This contains:
	// - Retrieve
	// - RetrieveAndGenerate.
	// Experimental.
	GrantQuery(grantee awsiam.IGrantable) awsiam.Grant
	// Grant the given identity permissions to retrieve content from the knowledge base.
	// Experimental.
	GrantRetrieve(grantee awsiam.IGrantable) awsiam.Grant
	// Grant the given identity permissions to retrieve content from the knowledge base.
	// Experimental.
	GrantRetrieveAndGenerate(grantee awsiam.IGrantable) awsiam.Grant
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for GraphKnowledgeBase
type jsiiProxy_GraphKnowledgeBase struct {
	jsiiProxy_GraphKnowledgeBaseBase
}

func (j *jsiiProxy_GraphKnowledgeBase) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) EmbeddingModel() BedrockFoundationModel {
	var returns BedrockFoundationModel
	_jsii_.Get(
		j,
		"embeddingModel",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) FieldMapping() *VectorFieldMapping {
	var returns *VectorFieldMapping
	_jsii_.Get(
		j,
		"fieldMapping",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Graph() neptune.INeptuneGraph {
	var returns neptune.INeptuneGraph
	_jsii_.Get(
		j,
		"graph",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Instruction() *string {
	var returns *string
	_jsii_.Get(
		j,
		"instruction",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) KnowledgeBaseArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"knowledgeBaseArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) KnowledgeBaseId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"knowledgeBaseId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Notebook() neptune.NeptuneGraphNotebook {
	var returns neptune.NeptuneGraphNotebook
	_jsii_.Get(
		j,
		"notebook",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Role() awsiam.IRole {
	var returns awsiam.IRole
	_jsii_.Get(
		j,
		"role",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) Type() KnowledgeBaseType {
	var returns KnowledgeBaseType
	_jsii_.Get(
		j,
		"type",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GraphKnowledgeBase) VectorStoreType() VectorStoreType {
	var returns VectorStoreType
	_jsii_.Get(
		j,
		"vectorStoreType",
		&returns,
	)
	return returns
}


// Experimental.
func NewGraphKnowledgeBase(scope constructs.Construct, id *string, props *GraphKnowledgeBaseProps) GraphKnowledgeBase {
	_init_.Initialize()

	if err := validateNewGraphKnowledgeBaseParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_GraphKnowledgeBase{}

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.GraphKnowledgeBase",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewGraphKnowledgeBase_Override(g GraphKnowledgeBase, scope constructs.Construct, id *string, props *GraphKnowledgeBaseProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.GraphKnowledgeBase",
		[]interface{}{scope, id, props},
		g,
	)
}

// Experimental.
func GraphKnowledgeBase_FromKnowledgeBaseAttributes(scope constructs.Construct, id *string, attrs *GraphKnowledgeBaseAttributes) IGraphKnowledgeBase {
	_init_.Initialize()

	if err := validateGraphKnowledgeBase_FromKnowledgeBaseAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IGraphKnowledgeBase

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.GraphKnowledgeBase",
		"fromKnowledgeBaseAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func GraphKnowledgeBase_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateGraphKnowledgeBase_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.GraphKnowledgeBase",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func GraphKnowledgeBase_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGraphKnowledgeBase_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.GraphKnowledgeBase",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func GraphKnowledgeBase_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGraphKnowledgeBase_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.bedrock.GraphKnowledgeBase",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) AddConfluenceDataSource(props *ConfluenceDataSourceAssociationProps) ConfluenceDataSource {
	if err := g.validateAddConfluenceDataSourceParameters(props); err != nil {
		panic(err)
	}
	var returns ConfluenceDataSource

	_jsii_.Invoke(
		g,
		"addConfluenceDataSource",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) AddCustomDataSource(props *CustomDataSourceAssociationProps) CustomDataSource {
	if err := g.validateAddCustomDataSourceParameters(props); err != nil {
		panic(err)
	}
	var returns CustomDataSource

	_jsii_.Invoke(
		g,
		"addCustomDataSource",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) AddS3DataSource(props *S3DataSourceAssociationProps) S3DataSource {
	if err := g.validateAddS3DataSourceParameters(props); err != nil {
		panic(err)
	}
	var returns S3DataSource

	_jsii_.Invoke(
		g,
		"addS3DataSource",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) AddSalesforceDataSource(props *SalesforceDataSourceAssociationProps) SalesforceDataSource {
	if err := g.validateAddSalesforceDataSourceParameters(props); err != nil {
		panic(err)
	}
	var returns SalesforceDataSource

	_jsii_.Invoke(
		g,
		"addSalesforceDataSource",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) AddSharePointDataSource(props *SharePointDataSourceAssociationProps) SharePointDataSource {
	if err := g.validateAddSharePointDataSourceParameters(props); err != nil {
		panic(err)
	}
	var returns SharePointDataSource

	_jsii_.Invoke(
		g,
		"addSharePointDataSource",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) AddWebCrawlerDataSource(props *WebCrawlerDataSourceAssociationProps) WebCrawlerDataSource {
	if err := g.validateAddWebCrawlerDataSourceParameters(props); err != nil {
		panic(err)
	}
	var returns WebCrawlerDataSource

	_jsii_.Invoke(
		g,
		"addWebCrawlerDataSource",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := g.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (g *jsiiProxy_GraphKnowledgeBase) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := g.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) GetResourceNameAttribute(nameAttr *string) *string {
	if err := g.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant {
	if err := g.validateGrantParameters(grantee); err != nil {
		panic(err)
	}
	args := []interface{}{grantee}
	for _, a := range actions {
		args = append(args, a)
	}

	var returns awsiam.Grant

	_jsii_.Invoke(
		g,
		"grant",
		args,
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) GrantQuery(grantee awsiam.IGrantable) awsiam.Grant {
	if err := g.validateGrantQueryParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		g,
		"grantQuery",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) GrantRetrieve(grantee awsiam.IGrantable) awsiam.Grant {
	if err := g.validateGrantRetrieveParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		g,
		"grantRetrieve",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) GrantRetrieveAndGenerate(grantee awsiam.IGrantable) awsiam.Grant {
	if err := g.validateGrantRetrieveAndGenerateParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		g,
		"grantRetrieveAndGenerate",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GraphKnowledgeBase) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

