package neptune

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/generative-ai-cdk-constructs-go/generativeaicdkconstructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/awssagemaker"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/cdklabs/generative-ai-cdk-constructs-go/generativeaicdkconstructs/neptune/internal"
)

// Creates a Neptune Graph Notebook for a given graph.
//
// A Neptune Graph Notebook provides:
// - Web-based interactive environment for querying and visualizing graph data
// - Support for multiple query languages:
//   - OpenCypher for property graph queries
//   - Gremlin for traversal-based queries
//   - SPARQL for RDF graph queries
// - Built-in visualization capabilities for exploring graph relationships
// - Sample notebooks and tutorials to help you get started
// - Integration with popular data science libraries   *
// This option is only supported when `publicConnectivity` is set to `true`. For private graphs,
// you should create your own notebook deployment using the `NeptuneGraphNotebook` Construct and
// configure the appropriate VPC and security group settings.
//
// **Note: Creating a notebook will incur additional AWS costs for the notebook instance.**
// See: https://docs.aws.amazon.com/neptune/latest/userguide/graph-notebooks.html
//
// Experimental.
type NeptuneGraphNotebook interface {
	awscdk.Resource
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Experimental.
	Env() *interfaces.ResourceEnvironment
	// Experimental.
	GraphExplorerEndpoint() *string
	// Experimental.
	InstanceType() awsec2.InstanceType
	// Experimental.
	JupyterLabEndpoint() *string
	// Experimental.
	LifecycleConfig() awssagemaker.CfnNotebookInstanceLifecycleConfig
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// Experimental.
	Role() awsiam.Role
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Experimental.
	VolumeSize() awscdk.Size
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for NeptuneGraphNotebook
type jsiiProxy_NeptuneGraphNotebook struct {
	internal.Type__awscdkResource
}

func (j *jsiiProxy_NeptuneGraphNotebook) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) GraphExplorerEndpoint() *string {
	var returns *string
	_jsii_.Get(
		j,
		"graphExplorerEndpoint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) InstanceType() awsec2.InstanceType {
	var returns awsec2.InstanceType
	_jsii_.Get(
		j,
		"instanceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) JupyterLabEndpoint() *string {
	var returns *string
	_jsii_.Get(
		j,
		"jupyterLabEndpoint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) LifecycleConfig() awssagemaker.CfnNotebookInstanceLifecycleConfig {
	var returns awssagemaker.CfnNotebookInstanceLifecycleConfig
	_jsii_.Get(
		j,
		"lifecycleConfig",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) Role() awsiam.Role {
	var returns awsiam.Role
	_jsii_.Get(
		j,
		"role",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NeptuneGraphNotebook) VolumeSize() awscdk.Size {
	var returns awscdk.Size
	_jsii_.Get(
		j,
		"volumeSize",
		&returns,
	)
	return returns
}


// Experimental.
func NewNeptuneGraphNotebook(scope constructs.Construct, id *string, props *NeptuneGraphNotebookProps) NeptuneGraphNotebook {
	_init_.Initialize()

	if err := validateNewNeptuneGraphNotebookParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_NeptuneGraphNotebook{}

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.neptune.NeptuneGraphNotebook",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewNeptuneGraphNotebook_Override(n NeptuneGraphNotebook, scope constructs.Construct, id *string, props *NeptuneGraphNotebookProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.neptune.NeptuneGraphNotebook",
		[]interface{}{scope, id, props},
		n,
	)
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func NeptuneGraphNotebook_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateNeptuneGraphNotebook_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.neptune.NeptuneGraphNotebook",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func NeptuneGraphNotebook_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateNeptuneGraphNotebook_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.neptune.NeptuneGraphNotebook",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func NeptuneGraphNotebook_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateNeptuneGraphNotebook_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.neptune.NeptuneGraphNotebook",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NeptuneGraphNotebook) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := n.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		n,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (n *jsiiProxy_NeptuneGraphNotebook) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		n,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NeptuneGraphNotebook) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := n.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		n,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NeptuneGraphNotebook) GetResourceNameAttribute(nameAttr *string) *string {
	if err := n.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		n,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NeptuneGraphNotebook) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		n,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

