package s3vectors

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/generative-ai-cdk-constructs-go/generativeaicdkconstructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
)

// S3 vector index resource for AWS S3 vector indexes.
//
// You can use this resource to create, modify, and manage vector indexes.
// See: https://docs.aws.amazon.com/s3vectors/latest/userguide/what-is-s3vectors.html
//
// Experimental.
type VectorIndex interface {
	VectorIndexBase
	// The timestamp when the vector bucket was created, in ISO 8601 format.
	// Experimental.
	CreationTime() *string
	// Experimental.
	DataType() VectorIndexDataType
	// Experimental.
	Dimension() *float64
	// Experimental.
	DistanceMetric() VectorIndexDistanceMetric
	// Optional KMS encryption key associated with this vector index.
	// Experimental.
	EncryptionKey() awskms.IKey
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Experimental.
	Env() *interfaces.ResourceEnvironment
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Experimental.
	VectorBucket() IVectorBucket
	// The ARN of the vector index.
	// Experimental.
	VectorIndexArn() *string
	// The name of the vector index.
	// Experimental.
	VectorIndexName() *string
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Grants IAM actions to the IAM Principal.
	//
	// Returns: An IAM Grant object representing the granted permissions.
	// Experimental.
	Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for VectorIndex
type jsiiProxy_VectorIndex struct {
	jsiiProxy_VectorIndexBase
}

func (j *jsiiProxy_VectorIndex) CreationTime() *string {
	var returns *string
	_jsii_.Get(
		j,
		"creationTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) DataType() VectorIndexDataType {
	var returns VectorIndexDataType
	_jsii_.Get(
		j,
		"dataType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) Dimension() *float64 {
	var returns *float64
	_jsii_.Get(
		j,
		"dimension",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) DistanceMetric() VectorIndexDistanceMetric {
	var returns VectorIndexDistanceMetric
	_jsii_.Get(
		j,
		"distanceMetric",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) EncryptionKey() awskms.IKey {
	var returns awskms.IKey
	_jsii_.Get(
		j,
		"encryptionKey",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) VectorBucket() IVectorBucket {
	var returns IVectorBucket
	_jsii_.Get(
		j,
		"vectorBucket",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) VectorIndexArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"vectorIndexArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorIndex) VectorIndexName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"vectorIndexName",
		&returns,
	)
	return returns
}


// Experimental.
func NewVectorIndex(scope constructs.Construct, id *string, props *VectorIndexProps) VectorIndex {
	_init_.Initialize()

	if err := validateNewVectorIndexParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_VectorIndex{}

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewVectorIndex_Override(v VectorIndex, scope constructs.Construct, id *string, props *VectorIndexProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		[]interface{}{scope, id, props},
		v,
	)
}

// Creates a VectorIndex construct that represents an external vector index by ARN.
//
// Returns: A VectorIndex construct.
// Experimental.
func VectorIndex_FromVectorIndexArn(scope constructs.Construct, id *string, vectorIndexArn *string) IVectorIndex {
	_init_.Initialize()

	if err := validateVectorIndex_FromVectorIndexArnParameters(scope, id, vectorIndexArn); err != nil {
		panic(err)
	}
	var returns IVectorIndex

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		"fromVectorIndexArn",
		[]interface{}{scope, id, vectorIndexArn},
		&returns,
	)

	return returns
}

// Experimental.
func VectorIndex_FromVectorIndexAttributes(scope constructs.Construct, id *string, attrs *VectorIndexAttributes) IVectorIndex {
	_init_.Initialize()

	if err := validateVectorIndex_FromVectorIndexAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IVectorIndex

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		"fromVectorIndexAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Creates a VectorIndex construct that represents an external vector index by name.
//
// Note: This method requires the bucket name because the ARN format includes both bucket and index.
//
// Returns: A VectorIndex construct.
// Experimental.
func VectorIndex_FromVectorIndexName(scope constructs.Construct, id *string, vectorBucketName *string, vectorIndexName *string) IVectorIndex {
	_init_.Initialize()

	if err := validateVectorIndex_FromVectorIndexNameParameters(scope, id, vectorBucketName, vectorIndexName); err != nil {
		panic(err)
	}
	var returns IVectorIndex

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		"fromVectorIndexName",
		[]interface{}{scope, id, vectorBucketName, vectorIndexName},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func VectorIndex_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateVectorIndex_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func VectorIndex_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVectorIndex_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func VectorIndex_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVectorIndex_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorIndex",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorIndex) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := v.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (v *jsiiProxy_VectorIndex) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorIndex) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := v.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorIndex) GetResourceNameAttribute(nameAttr *string) *string {
	if err := v.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorIndex) Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant {
	if err := v.validateGrantParameters(grantee); err != nil {
		panic(err)
	}
	args := []interface{}{grantee}
	for _, a := range actions {
		args = append(args, a)
	}

	var returns awsiam.Grant

	_jsii_.Invoke(
		v,
		"grant",
		args,
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorIndex) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

