package s3vectors

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/generative-ai-cdk-constructs-go/generativeaicdkconstructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	"github.com/aws/aws-cdk-go/awscdk/v2/awss3vectors"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
)

// S3 vector bucket resource for AWS S3 vector buckets.
//
// You can use this resource to create, modify, and manage vector buckets.
// See: https://docs.aws.amazon.com/s3vectors/latest/userguide/what-is-s3vectors.html
//
// Experimental.
type VectorBucket interface {
	VectorBucketBase
	// Indicates if a vector bucket resource policy should automatically be created upon the first call to `addToResourcePolicy`.
	// Experimental.
	AutoCreatePolicy() *bool
	// Experimental.
	SetAutoCreatePolicy(val *bool)
	// The timestamp when the vector bucket was created, in ISO 8601 format.
	// Experimental.
	CreationTime() *string
	// KMS encryption key associated with this cluster.
	// Experimental.
	EncryptionKey() awskms.IKey
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Experimental.
	Env() *interfaces.ResourceEnvironment
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The resource policy associated with this vector bucket.
	//
	// If `autoCreatePolicy` is true, a `VectorBucketPolicy` will be created upon the
	// first call to addToResourcePolicy.
	// Experimental.
	Policy() VectorBucketPolicy
	// Experimental.
	SetPolicy(val VectorBucketPolicy)
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// The ARN of the cluster.
	// Experimental.
	VectorBucketArn() *string
	// The name of the vector bucket.
	// Experimental.
	VectorBucketName() *string
	// Adds a statement to the resource policy for a principal (i.e. account/role/service) to perform actions on this bucket and/or its contents. Use `bucketArn` to obtain ARNs for this bucket or objects.
	//
	// Note that the policy statement may or may not be added to the policy.
	// For example, when an `IBucket` is created from an existing bucket,
	// it's not possible to tell whether the bucket already has a policy
	// attached, let alone to re-use that policy to add more statements to it.
	// So it's safest to do nothing in these cases.
	//
	// Returns: metadata about the execution of this method. If the policy
	// was not added, the value of `statementAdded` will be `false`. You
	// should always check this value to make sure that the operation was
	// actually carried out. Otherwise, synthesis and deploy will terminate
	// silently, which may be confusing.
	// Experimental.
	AddToResourcePolicy(permission awsiam.PolicyStatement) *awsiam.AddToResourcePolicyResult
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Grants IAM actions to the IAM Principal to delete the vector bucket and indexes.
	//
	// Returns: An IAM Grant object representing the granted permissions.
	// Experimental.
	GrantDelete(grantee awsiam.IGrantable, indexIds interface{}) awsiam.Grant
	// Grants IAM actions to the IAM Principal to read from the vector bucket and indexes.
	//
	// Returns: An IAM Grant object representing the granted permissions.
	// Experimental.
	GrantRead(grantee awsiam.IGrantable, indexIds interface{}) awsiam.Grant
	// Grants IAM actions to the IAM Principal to write to the vector bucket and indexes.
	//
	// Returns: An IAM Grant object representing the granted permissions.
	// Experimental.
	GrantWrite(grantee awsiam.IGrantable, indexIds interface{}) awsiam.Grant
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for VectorBucket
type jsiiProxy_VectorBucket struct {
	jsiiProxy_VectorBucketBase
}

func (j *jsiiProxy_VectorBucket) AutoCreatePolicy() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"autoCreatePolicy",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) CreationTime() *string {
	var returns *string
	_jsii_.Get(
		j,
		"creationTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) EncryptionKey() awskms.IKey {
	var returns awskms.IKey
	_jsii_.Get(
		j,
		"encryptionKey",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) Policy() VectorBucketPolicy {
	var returns VectorBucketPolicy
	_jsii_.Get(
		j,
		"policy",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) VectorBucketArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"vectorBucketArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VectorBucket) VectorBucketName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"vectorBucketName",
		&returns,
	)
	return returns
}


// Experimental.
func NewVectorBucket(scope constructs.Construct, id *string, props *VectorBucketProps) VectorBucket {
	_init_.Initialize()

	if err := validateNewVectorBucketParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_VectorBucket{}

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewVectorBucket_Override(v VectorBucket, scope constructs.Construct, id *string, props *VectorBucketProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		[]interface{}{scope, id, props},
		v,
	)
}

func (j *jsiiProxy_VectorBucket)SetAutoCreatePolicy(val *bool) {
	if err := j.validateSetAutoCreatePolicyParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"autoCreatePolicy",
		val,
	)
}

func (j *jsiiProxy_VectorBucket)SetPolicy(val VectorBucketPolicy) {
	_jsii_.Set(
		j,
		"policy",
		val,
	)
}

// Experimental.
func VectorBucket_FromCfnVectorBucket(cfnVectorBucket awss3vectors.CfnVectorBucket) IVectorBucket {
	_init_.Initialize()

	if err := validateVectorBucket_FromCfnVectorBucketParameters(cfnVectorBucket); err != nil {
		panic(err)
	}
	var returns IVectorBucket

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		"fromCfnVectorBucket",
		[]interface{}{cfnVectorBucket},
		&returns,
	)

	return returns
}

// Creates a VectorBucket construct that represents an external vector bucket by ARN.
//
// Returns: A VectorBucket construct.
// Experimental.
func VectorBucket_FromVectorBucketArn(scope constructs.Construct, id *string, vectorBucketArn *string) IVectorBucket {
	_init_.Initialize()

	if err := validateVectorBucket_FromVectorBucketArnParameters(scope, id, vectorBucketArn); err != nil {
		panic(err)
	}
	var returns IVectorBucket

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		"fromVectorBucketArn",
		[]interface{}{scope, id, vectorBucketArn},
		&returns,
	)

	return returns
}

// Creates a VectorBucket construct that represents an external vector bucket.
// Experimental.
func VectorBucket_FromVectorBucketAttributes(scope constructs.Construct, id *string, attrs *VectorBucketAttributes) IVectorBucket {
	_init_.Initialize()

	if err := validateVectorBucket_FromVectorBucketAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IVectorBucket

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		"fromVectorBucketAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Creates a VectorBucket construct that represents an external vector bucket by name.
//
// Returns: A VectorBucket construct.
// Experimental.
func VectorBucket_FromVectorBucketName(scope constructs.Construct, id *string, vectorBucketName *string) IVectorBucket {
	_init_.Initialize()

	if err := validateVectorBucket_FromVectorBucketNameParameters(scope, id, vectorBucketName); err != nil {
		panic(err)
	}
	var returns IVectorBucket

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		"fromVectorBucketName",
		[]interface{}{scope, id, vectorBucketName},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func VectorBucket_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateVectorBucket_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func VectorBucket_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVectorBucket_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func VectorBucket_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVectorBucket_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/generative-ai-cdk-constructs.s3vectors.VectorBucket",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) AddToResourcePolicy(permission awsiam.PolicyStatement) *awsiam.AddToResourcePolicyResult {
	if err := v.validateAddToResourcePolicyParameters(permission); err != nil {
		panic(err)
	}
	var returns *awsiam.AddToResourcePolicyResult

	_jsii_.Invoke(
		v,
		"addToResourcePolicy",
		[]interface{}{permission},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := v.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (v *jsiiProxy_VectorBucket) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := v.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) GetResourceNameAttribute(nameAttr *string) *string {
	if err := v.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) GrantDelete(grantee awsiam.IGrantable, indexIds interface{}) awsiam.Grant {
	if err := v.validateGrantDeleteParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		v,
		"grantDelete",
		[]interface{}{grantee, indexIds},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) GrantRead(grantee awsiam.IGrantable, indexIds interface{}) awsiam.Grant {
	if err := v.validateGrantReadParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		v,
		"grantRead",
		[]interface{}{grantee, indexIds},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) GrantWrite(grantee awsiam.IGrantable, indexIds interface{}) awsiam.Grant {
	if err := v.validateGrantWriteParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		v,
		"grantWrite",
		[]interface{}{grantee, indexIds},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VectorBucket) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

